/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Compiles a source file without blocking the Node.js event loop. */
export declare function compile(source: string, options: CompileOptions): Promise<CompileOutput>

/** Options controlling one compilation. */
export interface CompileOptions {
  /** Filename used to determine JavaScript, TypeScript, JSX, and module semantics. */
  filename: string
}

/** Output produced by the Evrel compiler. */
export interface CompileOutput {
  /** Generated JavaScript. */
  code: string
}

/** Compiles a complete source program without blocking Node.js. */
export declare function compileProgram(input: ProgramInput): Promise<ProgramOutput>

/** Compiles a source file synchronously. */
export declare function compileSync(source: string, options: CompileOptions): CompileOutput

/** Generated JavaScript for one source module. */
export interface GeneratedModule {
  key: string
  code: string
}

/** One import attribute. */
export interface ModuleAttribute {
  key: string
  value: string
}

/** How source requested another module. */
export declare const enum ModuleRequestKind {
  StaticImport = 'staticImport',
  ReExport = 'reExport',
  DynamicImport = 'dynamicImport',
  CommonJsRequire = 'commonJsRequire'
}

/** A complete host-resolved source program. */
export interface ProgramInput {
  modules: Array<ProgramModuleInput>
  entrypoints: Array<string>
}

/** One transformed source module. */
export interface ProgramModuleInput {
  key: string
  filename: string
  source: string
  resolvedRequests: Array<ResolvedModuleRequest>
}

/** Generated JavaScript for a complete program. */
export interface ProgramOutput {
  modules: Array<GeneratedModule>
}

/** One host-resolved module request. */
export interface ResolvedModuleRequest {
  kind: ModuleRequestKind
  specifier: string
  attributes: Array<ModuleAttribute>
  target: ResolvedModuleTarget
}

/** A host-resolved request target. */
export interface ResolvedModuleTarget {
  kind: ResolvedModuleTargetKind
  key: string
}

/** How the target participates in compilation. */
export declare const enum ResolvedModuleTargetKind {
  Internal = 'internal',
  Opaque = 'opaque',
  External = 'external'
}
