[package]
name = "evrel-frontend"
version = "0.1.0"
edition = "2024"

[dependencies]
evrel-ir = { version = "0.1.0", path = "../evrel-ir" }
oxc_allocator.workspace = true
oxc_ast.workspace = true
oxc_ast_visit.workspace = true
oxc_ecmascript.workspace = true
oxc_parser.workspace = true
oxc_semantic.workspace = true
oxc_span.workspace = true
oxc_syntax.workspace = true
rustc-hash.workspace = true
thiserror.workspace = true
